create schema refactor;
set schema refactor;

CREATE COLUMN TABLE JDT1 -- Journal Entry - Rows -Finance
(
    "SYSCred" DECIMAL(19,6) NULL, -- System Credit Amount
    "SYSDeb" DECIMAL(19,6) NULL, -- System Debit Amount
    "DueDate" DATE NOT NULL, -- Due Date
    "ShortName" NCHAR(15) NULL, -- BP/Account Code
    "BalDueDeb" DECIMAL(19,6) NULL, -- Balance Due - Debit
    "BalDueCred" DECIMAL(19,6) NULL -- Balance Due - Credit
);

CREATE COLUMN TABLE OCRD  -- Business Partner	Business Partners
(
"CardCode" NCHAR(15) NULL, -- BP Code
"CardName" NCHAR(100) NULL, -- BP Name
"CardType" CHAR(1) NULL -- BP Type
);

-- mock data generated by Mockaroo https://mockaroo.com/
-- 44 rows
insert into OCRD ("CardCode", "CardName", "CardType") values ('CC5848', 'Corhard', 'c');
insert into OCRD ("CardCode", "CardName", "CardType") values ('CC5880', 'Trower', 'c');
insert into OCRD ("CardCode", "CardName", "CardType") values ('CC5873', 'Whybray', 'c');
insert into OCRD ("CardCode", "CardName", "CardType") values ('CC8417', 'Hubbuck', 'c');
insert into OCRD ("CardCode", "CardName", "CardType") values ('CC1143', 'Jansik', 'c');
insert into OCRD ("CardCode", "CardName", "CardType") values ('CC3380', 'Lile', 'c');
insert into OCRD ("CardCode", "CardName", "CardType") values ('CC2477', 'Lornsen', 'c');
insert into OCRD ("CardCode", "CardName", "CardType") values ('CC1468', 'Shiers', 'c');
insert into OCRD ("CardCode", "CardName", "CardType") values ('CC2139', 'Temple', 'c');
insert into OCRD ("CardCode", "CardName", "CardType") values ('CC6099', 'McBeath', 'c');
insert into OCRD ("CardCode", "CardName", "CardType") values ('CC7037', 'Dove', 'c');
insert into OCRD ("CardCode", "CardName", "CardType") values ('CC9842', 'Bertin', 'c');
insert into OCRD ("CardCode", "CardName", "CardType") values ('CC9969', 'Clement', 'c');
insert into OCRD ("CardCode", "CardName", "CardType") values ('CC1084', 'Wisby', 'c');
insert into OCRD ("CardCode", "CardName", "CardType") values ('CC2314', 'Hurdiss', 'c');
insert into OCRD ("CardCode", "CardName", "CardType") values ('CC1602', 'Ponten', 'c');
insert into OCRD ("CardCode", "CardName", "CardType") values ('CC1365', 'Beaton', 'c');
insert into OCRD ("CardCode", "CardName", "CardType") values ('CC2140', 'Gland', 'c');
insert into OCRD ("CardCode", "CardName", "CardType") values ('CC3479', 'Fain', 'c');
insert into OCRD ("CardCode", "CardName", "CardType") values ('CC6794', 'Keppie', 'c');
insert into OCRD ("CardCode", "CardName", "CardType") values ('CC0583', 'Fortnam', 'c');
insert into OCRD ("CardCode", "CardName", "CardType") values ('CC0046', 'Sissons', 'c');
insert into OCRD ("CardCode", "CardName", "CardType") values ('CC0664', 'Flippini', 'c');
insert into OCRD ("CardCode", "CardName", "CardType") values ('CC1229', 'Cicchinelli', 'c');
insert into OCRD ("CardCode", "CardName", "CardType") values ('CC5025', 'Muncey', 'c');
insert into OCRD ("CardCode", "CardName", "CardType") values ('CC5334', 'Mulryan', 'c');
insert into OCRD ("CardCode", "CardName", "CardType") values ('CC2192', 'Shurman', 'c');
insert into OCRD ("CardCode", "CardName", "CardType") values ('CC3768', 'Frampton', 'c');
insert into OCRD ("CardCode", "CardName", "CardType") values ('CC4693', 'Hetterich', 'c');
insert into OCRD ("CardCode", "CardName", "CardType") values ('CC0790', 'Valeri', 'c');
insert into OCRD ("CardCode", "CardName", "CardType") values ('CC8023', 'Byass', 'c');
insert into OCRD ("CardCode", "CardName", "CardType") values ('CC1649', 'Litherborough', 'c');
insert into OCRD ("CardCode", "CardName", "CardType") values ('CC2503', 'Oppie', 'c');
insert into OCRD ("CardCode", "CardName", "CardType") values ('CC1107', 'Geaney', 'c');
insert into OCRD ("CardCode", "CardName", "CardType") values ('CC8838', 'Abrami', 'c');
insert into OCRD ("CardCode", "CardName", "CardType") values ('CC3249', 'Bayle', 'c');
insert into OCRD ("CardCode", "CardName", "CardType") values ('CC8249', 'Inglesent', 'c');
insert into OCRD ("CardCode", "CardName", "CardType") values ('CC2190', 'Alekseev', 'c');
insert into OCRD ("CardCode", "CardName", "CardType") values ('CC7341', 'Taylour', 'c');
insert into OCRD ("CardCode", "CardName", "CardType") values ('CC4128', 'Monelle', 'c');
insert into OCRD ("CardCode", "CardName", "CardType") values ('CC1143', 'Edmondson', 'c');
insert into OCRD ("CardCode", "CardName", "CardType") values ('CC4456', 'Flannery', 'c');
insert into OCRD ("CardCode", "CardName", "CardType") values ('CC5922', 'Folonin', 'c');
insert into OCRD ("CardCode", "CardName", "CardType") values ('CC2106', 'Kingsman', 'c');
insert into OCRD ("CardCode", "CardName", "CardType") values ('CC1500', 'Parsley', 'c');

-- generating 2500 rows for every row in OCRD --> 44 * 2500 = 110.000 rows
INSERT INTO JDT1 
( "SYSCred", "SYSDeb", "DueDate", "ShortName", "BalDueDeb", "BalDueCred" )
(
    SELECT
         to_decimal( rand()*500, 19, 3) AS "SYSCred",  
         to_decimal( rand()*500, 19, 3) AS "SYSDeb", 
         add_days (current_date, -250 +rand ()*500)  AS "DueDate" ,
         ocrd."CardCode" AS "ShortName",  
         to_decimal( rand()*500, 19, 3) AS "BalDueDeb"  ,  
         to_decimal( rand()*500, 19, 3) AS "BalDueCred"  
    FROM 
        OCRD  CROSS JOIN
        series_generate_integer(1, 1 , 2500 )
);
