set schema refactor;
-- step 13 - fix type conversion from CASE expressions

WITH _customer_credits_debits
("Customer Code", "Customer Name", "SYS Balance Due", "Cust Balance Due", "Due Days") AS 
    (SELECT 
          OCRD."CardCode" AS "Customer Code"
        , OCRD."CardName" AS "Customer Name"
        , (case 
            when "SYSCred" != 0.0 
            then TO_DECIMAL("SYSCred" * -1.0, 19, 6)
            else TO_DECIMAL("SYSDeb", 19, 6)
           end)  as "SYS Balance Due"
        , (case 
                when "BalDueCred" != 0.0 
                then TO_DECIMAL("BalDueCred" * -1.0, 19, 6)
                else TO_DECIMAL("BalDueDeb", 19, 6)
           end) as "Cust Balance Due"
        , DAYS_BETWEEN(JDT1."DueDate", current_date) AS "Due Days"
     FROM 
            OCRD INNER JOIN JDT1 
        ON  JDT1."ShortName" = OCRD."CardCode" 
        AND OCRD."CardType" = 'c' 
    )

SELECT 
      "Customer Code"
    , "Customer Name"
    , SUM("SYS Balance Due") AS "Balance Due"
    , SUM(CASE 
            WHEN ("Due Days" < 0)
            THEN "Cust Balance Due"
          END) AS "Future Remit"
    , SUM(CASE 
            WHEN ("Due Days" BETWEEN 0 AND 30) 
            THEN "Cust Balance Due"
          END) AS "0-30 days"
    , SUM(CASE 
            WHEN ("Due Days" BETWEEN 31 AND 60) 
            THEN "Cust Balance Due"
          END) AS "31 to 60 days"
    , SUM(CASE 
            WHEN ("Due Days" BETWEEN 61 AND 90) 
            THEN "Cust Balance Due"
          END) AS "61 to 90 days"
    , SUM(CASE 
            WHEN ("Due Days" BETWEEN 91 AND 120) 
            THEN "Cust Balance Due"
          END) AS "91 to 120 days"
    , SUM(CASE 
            WHEN ("Due Days" > 121)
            THEN "Cust Balance Due"
          END) AS "121+ days" 
FROM 
    _customer_credits_debits
GROUP BY 
      "Customer Code"
    , "Customer Name" 
HAVING 
      SUM("SYS Balance Due")  != 0 
ORDER BY 
    "Customer Code";

/*
OPERATOR_NAME         	OPERATOR_DETAILS                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                     	OPERATOR_PROPERTIES                   	EXECUTION_ENGINE	DATABASE_NAME	SCHEMA_NAME	TABLE_NAME	TABLE_TYPE  	TABLE_SIZE	OUTPUT_SIZE        	SUBTREE_COST          
COLUMN SEARCH         	_CUSTOMER_CREDITS_DEBITS.Customer Code, _CUSTOMER_CREDITS_DEBITS.Customer Name, SUM(CASE WHEN JDT1.SYSCred <> 0.0 THEN TO_DECIMAL(JDT1.SYSCred * -1.0, 19, 6) ELSE TO_DECIMAL(JDT1.SYSDeb, 19, 6) END), SUM(CASE WHEN DAYS_BETWEEN(JDT1.DueDate, CURRENT_DATE) < 0 THEN CASE WHEN JDT1.BalDueCred <> 0.0 THEN TO_DECIMAL(JDT1.BalDueCred * -1.0, 19, 6) ELSE TO_DECIMAL(JDT1.BalDueDeb, 19, 6) END ELSE 0.00 END), SUM(CASE WHEN DAYS_BETWEEN(JDT1.DueDate, CURRENT_DATE) >= 0 AND DAYS_BETWEEN(JDT1.DueDate, CURRENT_DATE) <= 30 THEN CASE WHEN JDT1.BalDueCred <> 0.0 THEN TO_DECIMAL(JDT1.BalDueCred * -1.0, 19, 6) ELSE TO_DECIMAL(JDT1.BalDueDeb, 19, 6) END ELSE NULL END), SUM(CASE WHEN DAYS_BETWEEN(JDT1.DueDate, CURRENT_DATE) >= 31 AND DAYS_BETWEEN(JDT1.DueDate, CURRENT_DATE) <= 60 THEN CASE WHEN JDT1.BalDueCred <> 0.0 THEN TO_DECIMAL(JDT1.BalDueCred * -1.0, 19, 6) ELSE TO_DECIMAL(JDT1.BalDueDeb, 19, 6) END ELSE NULL END), SUM(CASE WHEN DAYS_BETWEEN(JDT1.DueDate, CURRENT_DATE) >= 61 AND DAYS_BETWEEN(JDT1.DueDate, CURRENT_DATE) <= 90 THEN CASE WHEN JDT1.BalDueCred <> 0.0 THEN TO_DECIMAL(JDT1.BalDueCred * -1.0, 19, 6) ELSE TO_DECIMAL(JDT1.BalDueDeb, 19, 6) END ELSE NULL END), SUM(CASE WHEN DAYS_BETWEEN(JDT1.DueDate, CURRENT_DATE) >= 91 AND DAYS_BETWEEN(JDT1.DueDate, CURRENT_DATE) <= 120 THEN CASE WHEN JDT1.BalDueCred <> 0.0 THEN TO_DECIMAL(JDT1.BalDueCred * -1.0, 19, 6) ELSE TO_DECIMAL(JDT1.BalDueDeb, 19, 6) END ELSE NULL END), SUM(CASE WHEN DAYS_BETWEEN(JDT1.DueDate, CURRENT_DATE) > 121 THEN CASE WHEN JDT1.BalDueCred <> 0.0 THEN TO_DECIMAL(JDT1.BalDueCred * -1.0, 19, 6) ELSE TO_DECIMAL(JDT1.BalDueDeb, 19, 6) END ELSE NULL END)                       	LATE MATERIALIZATION, ENUM_BY: CS_JOIN	OLAP            	HXE          	?          	?         	?           	?         	44                 	0.01576284646476067   
  ORDER BY            	_CUSTOMER_CREDITS_DEBITS.Customer Code ASC                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                           	                                      	OLAP            	             	?          	?         	?           	?         	44                 	0.015424827375560673  
    HAVING            	SUM(CASE WHEN JDT1.SYSCred <> 0.0 THEN TO_DECIMAL(JDT1.SYSCred * -1.0, 19, 6) ELSE TO_DECIMAL(JDT1.SYSDeb, 19, 6) END) != 0                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          	                                      	OLAP            	             	?          	?         	?           	?         	44                 	0.015423380626181734  
      AGGREGATION     	GROUPING: _CUSTOMER_CREDITS_DEBITS.Customer Code, _CUSTOMER_CREDITS_DEBITS.Customer Name, AGGREGATION: SUM(CASE WHEN JDT1.SYSCred <> 0.0 THEN TO_DECIMAL(JDT1.SYSCred * -1.0, 19, 6) ELSE TO_DECIMAL(JDT1.SYSDeb, 19, 6) END), SUM(CASE WHEN DAYS_BETWEEN(JDT1.DueDate, CURRENT_DATE) < 0 THEN CASE WHEN JDT1.BalDueCred <> 0.0 THEN TO_DECIMAL(JDT1.BalDueCred * -1.0, 19, 6) ELSE TO_DECIMAL(JDT1.BalDueDeb, 19, 6) END ELSE 0.00 END), SUM(CASE WHEN DAYS_BETWEEN(JDT1.DueDate, CURRENT_DATE) >= 0 AND DAYS_BETWEEN(JDT1.DueDate, CURRENT_DATE) <= 30 THEN CASE WHEN JDT1.BalDueCred <> 0.0 THEN TO_DECIMAL(JDT1.BalDueCred * -1.0, 19, 6) ELSE TO_DECIMAL(JDT1.BalDueDeb, 19, 6) END ELSE NULL END), SUM(CASE WHEN DAYS_BETWEEN(JDT1.DueDate, CURRENT_DATE) >= 31 AND DAYS_BETWEEN(JDT1.DueDate, CURRENT_DATE) <= 60 THEN CASE WHEN JDT1.BalDueCred <> 0.0 THEN TO_DECIMAL(JDT1.BalDueCred * -1.0, 19, 6) ELSE TO_DECIMAL(JDT1.BalDueDeb, 19, 6) END ELSE NULL END), SUM(CASE WHEN DAYS_BETWEEN(JDT1.DueDate, CURRENT_DATE) >= 61 AND DAYS_BETWEEN(JDT1.DueDate, CURRENT_DATE) <= 90 THEN CASE WHEN JDT1.BalDueCred <> 0.0 THEN TO_DECIMAL(JDT1.BalDueCred * -1.0, 19, 6) ELSE TO_DECIMAL(JDT1.BalDueDeb, 19, 6) END ELSE NULL END), SUM(CASE WHEN DAYS_BETWEEN(JDT1.DueDate, CURRENT_DATE) >= 91 AND DAYS_BETWEEN(JDT1.DueDate, CURRENT_DATE) <= 120 THEN CASE WHEN JDT1.BalDueCred <> 0.0 THEN TO_DECIMAL(JDT1.BalDueCred * -1.0, 19, 6) ELSE TO_DECIMAL(JDT1.BalDueDeb, 19, 6) END ELSE NULL END), SUM(CASE WHEN DAYS_BETWEEN(JDT1.DueDate, CURRENT_DATE) > 121 THEN CASE WHEN JDT1.BalDueCred <> 0.0 THEN TO_DECIMAL(JDT1.BalDueCred * -1.0, 19, 6) ELSE TO_DECIMAL(JDT1.BalDueDeb, 19, 6) END ELSE NULL END)	                                      	OLAP            	             	?          	?         	?           	?         	45                 	0.01542286926254537   
        JOIN          	JOIN CONDITION: (INNER) JDT1.ShortName = OCRD.CardCode                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                               	                                      	OLAP            	             	?          	?         	?           	?         	117,452.99999999999	0.00014780494248429349
          COLUMN TABLE	[FACT]                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                               	                                      	OLAP            	HXE          	REFACTOR   	JDT1      	COLUMN TABLE	112,455   	112,455            	?                     
          COLUMN TABLE	FILTER CONDITION: OCRD.CardType = 'c'                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                	                                      	OLAP            	HXE          	REFACTOR   	OCRD      	COLUMN TABLE	45        	45                 	?                     

*/    