set schema refactor;

SELECT OCRD."CardCode" AS "Customer Code", OCRD."CardName" AS "Customer Name", SUM(
    CASE 
        WHEN "SYSCred" <> 0 THEN "SYSCred" * -1 
        ELSE "SYSDeb" 
    END) AS "Balance Due", IFNULL(SUM(
    CASE 
        WHEN DAYS_BETWEEN(JDT1."DueDate", (SELECT NOW() "NOW" FROM DUMMY)) < 0 THEN 
        CASE 
            WHEN JDT1."BalDueCred" <> 0 THEN JDT1."BalDueCred" * -1 
            ELSE JDT1."BalDueDeb" 
        END 
    END), 0.00) AS "Future Remit", IFNULL(SUM(
    CASE 
        WHEN (DAYS_BETWEEN(JDT1."DueDate", (SELECT NOW() "NOW" FROM DUMMY)) >= 0 AND
         DAYS_BETWEEN(JDT1."DueDate", (SELECT NOW() "NOW" FROM DUMMY)) < 30) THEN 
        CASE 
            WHEN JDT1."BalDueCred" <> 0 THEN JDT1."BalDueCred" * -1 
            ELSE JDT1."BalDueDeb" 
        END 
    END), 0.00) AS "0-30 days", IFNULL(SUM(
    CASE 
        WHEN (DAYS_BETWEEN(JDT1."DueDate", (SELECT NOW() "NOW" FROM DUMMY)) >= 30 AND
         DAYS_BETWEEN(JDT1."DueDate", (SELECT NOW() "NOW" FROM DUMMY)) < 60) THEN 
        CASE 
            WHEN JDT1."BalDueCred" <> 0 THEN JDT1."BalDueCred" * -1 
            ELSE JDT1."BalDueDeb" 
        END 
    END), 0.00) AS "31 to 60 days", IFNULL(SUM(
    CASE 
        WHEN (DAYS_BETWEEN(JDT1."DueDate", (SELECT NOW() "NOW" FROM DUMMY)) >= 60 AND
         DAYS_BETWEEN(JDT1."DueDate", (SELECT NOW() "NOW" FROM DUMMY)) < 90) THEN 
        CASE 
            WHEN JDT1."BalDueCred" <> 0 THEN JDT1."BalDueCred" * -1 
            ELSE JDT1."BalDueDeb" 
        END 
    END), 0.00) AS "61 to 90 days", IFNULL(SUM(
    CASE 
        WHEN (DAYS_BETWEEN(JDT1."DueDate", (SELECT NOW() "NOW" FROM DUMMY)) >= 90 AND
         DAYS_BETWEEN(JDT1."DueDate", (SELECT NOW() "NOW" FROM DUMMY)) < 120) THEN 
        CASE 
            WHEN JDT1."BalDueCred" <> 0 THEN JDT1."BalDueCred" * -1 
            ELSE JDT1."BalDueDeb" 
        END 
    END), 0.00) AS "91 to 120 days", IFNULL(SUM(
    CASE 
        WHEN DAYS_BETWEEN(JDT1."DueDate", (SELECT NOW() "NOW" FROM DUMMY)) >= 120 THEN 
        CASE 
            WHEN "BalDueCred" <> 0 THEN "BalDueCred" * -1 
            ELSE "BalDueDeb" 
        END 
    END), 0.00) AS "120+ days" 
FROM JDT1, 
    OCRD 
WHERE JDT1."ShortName" = OCRD."CardCode" AND OCRD."CardType" = 'c' 
GROUP BY OCRD."CardCode", OCRD."CardName" HAVING SUM(
CASE 
    WHEN "SYSCred" <> 0 THEN "SYSCred" * -1 
    ELSE "SYSDeb" 
END) > 0 OR SUM(
CASE 
    WHEN "SYSCred" <> 0 THEN "SYSCred" * -1 
    ELSE "SYSDeb" 
END) < 0 
ORDER BY OCRD."CardCode";

/*
--> small data set

OPERATOR_NAME         	OPERATOR_DETAILS                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          	OPERATOR_PROPERTIES                   	EXECUTION_ENGINE	TABLE_NAME	TABLE_TYPE  	TABLE_SIZE	OUTPUT_SIZE        	SUBTREE_COST          
COLUMN SEARCH         	OCRD.CardCode, OCRD.CardName, SUM(CASE WHEN JDT1.SYSCred <> 0 THEN JDT1.SYSCred * -1 ELSE TO_DECIMAL(JDT1.SYSDeb, 22, 6) END), IFNULL(SUM(CASE WHEN DAYS_BETWEEN(TO_TIMESTAMP(JDT1.DueDate), CURRENT_TIMESTAMP) < 0 THEN CASE WHEN JDT1.BalDueCred <> 0 THEN JDT1.BalDueCred * -1 ELSE TO_DECIMAL(JDT1.BalDueDeb, 22, 6) END ELSE NULL END), 0.00), IFNULL(SUM(CASE WHEN DAYS_BETWEEN(TO_TIMESTAMP(JDT1.DueDate), CURRENT_TIMESTAMP) >= 0 AND DAYS_BETWEEN(TO_TIMESTAMP(JDT1.DueDate), CURRENT_TIMESTAMP) < 30 THEN CASE WHEN JDT1.BalDueCred <> 0 THEN JDT1.BalDueCred * -1 ELSE TO_DECIMAL(JDT1.BalDueDeb, 22, 6) END ELSE NULL END), 0.00), IFNULL(SUM(CASE WHEN DAYS_BETWEEN(TO_TIMESTAMP(JDT1.DueDate), CURRENT_TIMESTAMP) >= 30 AND DAYS_BETWEEN(TO_TIMESTAMP(JDT1.DueDate), CURRENT_TIMESTAMP) < 60 THEN CASE WHEN JDT1.BalDueCred <> 0 THEN JDT1.BalDueCred * -1 ELSE TO_DECIMAL(JDT1.BalDueDeb, 22, 6) END ELSE NULL END), 0.00), IFNULL(SUM(CASE WHEN DAYS_BETWEEN(TO_TIMESTAMP(JDT1.DueDate), CURRENT_TIMESTAMP) >= 60 AND DAYS_BETWEEN(TO_TIMESTAMP(JDT1.DueDate), CURRENT_TIMESTAMP) < 90 THEN CASE WHEN JDT1.BalDueCred <> 0 THEN JDT1.BalDueCred * -1 ELSE TO_DECIMAL(JDT1.BalDueDeb, 22, 6) END ELSE NULL END), 0.00), IFNULL(SUM(CASE WHEN DAYS_BETWEEN(TO_TIMESTAMP(JDT1.DueDate), CURRENT_TIMESTAMP) >= 90 AND DAYS_BETWEEN(TO_TIMESTAMP(JDT1.DueDate), CURRENT_TIMESTAMP) < 120 THEN CASE WHEN JDT1.BalDueCred <> 0 THEN JDT1.BalDueCred * -1 ELSE TO_DECIMAL(JDT1.BalDueDeb, 22, 6) END ELSE NULL END), 0.00), IFNULL(SUM(CASE WHEN DAYS_BETWEEN(TO_TIMESTAMP(JDT1.DueDate), CURRENT_TIMESTAMP) >= 120 THEN CASE WHEN JDT1.BalDueCred <> 0 THEN JDT1.BalDueCred * -1 ELSE TO_DECIMAL(JDT1.BalDueDeb, 22, 6) END ELSE NULL END), 0.00)	LATE MATERIALIZATION, ENUM_BY: CS_JOIN	OLAP            	?         	?           	?         	28.799999999999997 	0.015648924937121524  
  ORDER BY            	OCRD.CardCode ASC                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                         	                                      	OLAP            	?         	?           	?         	28.799999999999997 	0.015424221533281525  
    HAVING            	(SUM(CASE WHEN JDT1.SYSCred <> 0 THEN JDT1.SYSCred * -1 ELSE TO_DECIMAL(JDT1.SYSDeb, 22, 6) END) > 0) OR (SUM(CASE WHEN JDT1.SYSCred <> 0 THEN JDT1.SYSCred * -1 ELSE TO_DECIMAL(JDT1.SYSDeb, 22, 6) END) < 0)                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            	                                      	OLAP            	?         	?           	?         	28.799999999999997 	0.015423380626181734  
      AGGREGATION     	GROUPING: OCRD.CardCode, OCRD.CardName, AGGREGATION: SUM(CASE WHEN JDT1.SYSCred <> 0 THEN JDT1.SYSCred * -1 ELSE TO_DECIMAL(JDT1.SYSDeb, 22, 6) END), SUM(CASE WHEN DAYS_BETWEEN(TO_TIMESTAMP(JDT1.DueDate), CURRENT_TIMESTAMP) < 0 THEN CASE WHEN JDT1.BalDueCred <> 0 THEN JDT1.BalDueCred * -1 ELSE TO_DECIMAL(JDT1.BalDueDeb, 22, 6) END ELSE NULL END), SUM(CASE WHEN DAYS_BETWEEN(TO_TIMESTAMP(JDT1.DueDate), CURRENT_TIMESTAMP) >= 0 AND DAYS_BETWEEN(TO_TIMESTAMP(JDT1.DueDate), CURRENT_TIMESTAMP) < 30 THEN CASE WHEN JDT1.BalDueCred <> 0 THEN JDT1.BalDueCred * -1 ELSE TO_DECIMAL(JDT1.BalDueDeb, 22, 6) END ELSE NULL END), SUM(CASE WHEN DAYS_BETWEEN(TO_TIMESTAMP(JDT1.DueDate), CURRENT_TIMESTAMP) >= 30 AND DAYS_BETWEEN(TO_TIMESTAMP(JDT1.DueDate), CURRENT_TIMESTAMP) < 60 THEN CASE WHEN JDT1.BalDueCred <> 0 THEN JDT1.BalDueCred * -1 ELSE TO_DECIMAL(JDT1.BalDueDeb, 22, 6) END ELSE NULL END), SUM(CASE WHEN DAYS_BETWEEN(TO_TIMESTAMP(JDT1.DueDate), CURRENT_TIMESTAMP) >= 60 AND DAYS_BETWEEN(TO_TIMESTAMP(JDT1.DueDate), CURRENT_TIMESTAMP) < 90 THEN CASE WHEN JDT1.BalDueCred <> 0 THEN JDT1.BalDueCred * -1 ELSE TO_DECIMAL(JDT1.BalDueDeb, 22, 6) END ELSE NULL END), SUM(CASE WHEN DAYS_BETWEEN(TO_TIMESTAMP(JDT1.DueDate), CURRENT_TIMESTAMP) >= 90 AND DAYS_BETWEEN(TO_TIMESTAMP(JDT1.DueDate), CURRENT_TIMESTAMP) < 120 THEN CASE WHEN JDT1.BalDueCred <> 0 THEN JDT1.BalDueCred * -1 ELSE TO_DECIMAL(JDT1.BalDueDeb, 22, 6) END ELSE NULL END), SUM(CASE WHEN DAYS_BETWEEN(TO_TIMESTAMP(JDT1.DueDate), CURRENT_TIMESTAMP) >= 120 THEN CASE WHEN JDT1.BalDueCred <> 0 THEN JDT1.BalDueCred * -1 ELSE TO_DECIMAL(JDT1.BalDueDeb, 22, 6) END ELSE NULL END)                                                             	                                      	OLAP            	?         	?           	?         	45                 	0.01542286926254537   
        JOIN          	JOIN CONDITION: (INNER) JDT1.ShortName = OCRD.CardCode                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    	                                      	OLAP            	?         	?           	?         	117,452.99999999999	0.00014780494248429349
          COLUMN TABLE	[FACT]                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    	                                      	OLAP            	JDT1      	COLUMN TABLE	112,455   	112,455            	?                     
          COLUMN TABLE	FILTER CONDITION: OCRD.CardType = 'c'                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                     	                                      	OLAP            	OCRD      	COLUMN TABLE	45        	45                 	?                     
*/

/*
--> large data set
OPERATOR_NAME         	OPERATOR_DETAILS                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          	OPERATOR_PROPERTIES                   	EXECUTION_ENGINE	DATABASE_NAME	SCHEMA_NAME	TABLE_NAME	TABLE_TYPE  	TABLE_SIZE	OUTPUT_SIZE	SUBTREE_COST         
COLUMN SEARCH         	OCRD.CardCode, OCRD.CardName, SUM(CASE WHEN JDT1.SYSCred <> 0 THEN JDT1.SYSCred * -1 ELSE TO_DECIMAL(JDT1.SYSDeb, 22, 6) END), IFNULL(SUM(CASE WHEN DAYS_BETWEEN(TO_TIMESTAMP(JDT1.DueDate), CURRENT_TIMESTAMP) < 0 THEN CASE WHEN JDT1.BalDueCred <> 0 THEN JDT1.BalDueCred * -1 ELSE TO_DECIMAL(JDT1.BalDueDeb, 22, 6) END ELSE NULL END), 0.00), IFNULL(SUM(CASE WHEN DAYS_BETWEEN(TO_TIMESTAMP(JDT1.DueDate), CURRENT_TIMESTAMP) >= 0 AND DAYS_BETWEEN(TO_TIMESTAMP(JDT1.DueDate), CURRENT_TIMESTAMP) < 30 THEN CASE WHEN JDT1.BalDueCred <> 0 THEN JDT1.BalDueCred * -1 ELSE TO_DECIMAL(JDT1.BalDueDeb, 22, 6) END ELSE NULL END), 0.00), IFNULL(SUM(CASE WHEN DAYS_BETWEEN(TO_TIMESTAMP(JDT1.DueDate), CURRENT_TIMESTAMP) >= 30 AND DAYS_BETWEEN(TO_TIMESTAMP(JDT1.DueDate), CURRENT_TIMESTAMP) < 60 THEN CASE WHEN JDT1.BalDueCred <> 0 THEN JDT1.BalDueCred * -1 ELSE TO_DECIMAL(JDT1.BalDueDeb, 22, 6) END ELSE NULL END), 0.00), IFNULL(SUM(CASE WHEN DAYS_BETWEEN(TO_TIMESTAMP(JDT1.DueDate), CURRENT_TIMESTAMP) >= 60 AND DAYS_BETWEEN(TO_TIMESTAMP(JDT1.DueDate), CURRENT_TIMESTAMP) < 90 THEN CASE WHEN JDT1.BalDueCred <> 0 THEN JDT1.BalDueCred * -1 ELSE TO_DECIMAL(JDT1.BalDueDeb, 22, 6) END ELSE NULL END), 0.00), IFNULL(SUM(CASE WHEN DAYS_BETWEEN(TO_TIMESTAMP(JDT1.DueDate), CURRENT_TIMESTAMP) >= 90 AND DAYS_BETWEEN(TO_TIMESTAMP(JDT1.DueDate), CURRENT_TIMESTAMP) < 120 THEN CASE WHEN JDT1.BalDueCred <> 0 THEN JDT1.BalDueCred * -1 ELSE TO_DECIMAL(JDT1.BalDueDeb, 22, 6) END ELSE NULL END), 0.00), IFNULL(SUM(CASE WHEN DAYS_BETWEEN(TO_TIMESTAMP(JDT1.DueDate), CURRENT_TIMESTAMP) >= 120 THEN CASE WHEN JDT1.BalDueCred <> 0 THEN JDT1.BalDueCred * -1 ELSE TO_DECIMAL(JDT1.BalDueDeb, 22, 6) END ELSE NULL END), 0.00)	LATE MATERIALIZATION, ENUM_BY: CS_JOIN	OLAP            	HXE          	?          	?         	?           	?         	884.48     	0.3988637759988947   
  ORDER BY            	OCRD.CardCode ASC                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                         	                                      	OLAP            	             	?          	?         	?           	?         	884.48     	0.3922599959076307   
    HAVING            	(SUM(CASE WHEN JDT1.SYSCred <> 0 THEN JDT1.SYSCred * -1 ELSE TO_DECIMAL(JDT1.SYSDeb, 22, 6) END) > 0) OR (SUM(CASE WHEN JDT1.SYSCred <> 0 THEN JDT1.SYSCred * -1 ELSE TO_DECIMAL(JDT1.SYSDeb, 22, 6) END) < 0)                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            	                                      	OLAP            	             	?          	?         	?           	?         	884.48     	0.3922078517568264   
      AGGREGATION     	GROUPING: OCRD.CardCode, AGGREGATION: SUM(CASE WHEN JDT1.SYSCred <> 0 THEN JDT1.SYSCred * -1 ELSE TO_DECIMAL(JDT1.SYSDeb, 22, 6) END), SUM(CASE WHEN DAYS_BETWEEN(TO_TIMESTAMP(JDT1.DueDate), CURRENT_TIMESTAMP) < 0 THEN CASE WHEN JDT1.BalDueCred <> 0 THEN JDT1.BalDueCred * -1 ELSE TO_DECIMAL(JDT1.BalDueDeb, 22, 6) END ELSE NULL END), SUM(CASE WHEN DAYS_BETWEEN(TO_TIMESTAMP(JDT1.DueDate), CURRENT_TIMESTAMP) >= 0 AND DAYS_BETWEEN(TO_TIMESTAMP(JDT1.DueDate), CURRENT_TIMESTAMP) < 30 THEN CASE WHEN JDT1.BalDueCred <> 0 THEN JDT1.BalDueCred * -1 ELSE TO_DECIMAL(JDT1.BalDueDeb, 22, 6) END ELSE NULL END), SUM(CASE WHEN DAYS_BETWEEN(TO_TIMESTAMP(JDT1.DueDate), CURRENT_TIMESTAMP) >= 30 AND DAYS_BETWEEN(TO_TIMESTAMP(JDT1.DueDate), CURRENT_TIMESTAMP) < 60 THEN CASE WHEN JDT1.BalDueCred <> 0 THEN JDT1.BalDueCred * -1 ELSE TO_DECIMAL(JDT1.BalDueDeb, 22, 6) END ELSE NULL END), SUM(CASE WHEN DAYS_BETWEEN(TO_TIMESTAMP(JDT1.DueDate), CURRENT_TIMESTAMP) >= 60 AND DAYS_BETWEEN(TO_TIMESTAMP(JDT1.DueDate), CURRENT_TIMESTAMP) < 90 THEN CASE WHEN JDT1.BalDueCred <> 0 THEN JDT1.BalDueCred * -1 ELSE TO_DECIMAL(JDT1.BalDueDeb, 22, 6) END ELSE NULL END), SUM(CASE WHEN DAYS_BETWEEN(TO_TIMESTAMP(JDT1.DueDate), CURRENT_TIMESTAMP) >= 90 AND DAYS_BETWEEN(TO_TIMESTAMP(JDT1.DueDate), CURRENT_TIMESTAMP) < 120 THEN CASE WHEN JDT1.BalDueCred <> 0 THEN JDT1.BalDueCred * -1 ELSE TO_DECIMAL(JDT1.BalDueDeb, 22, 6) END ELSE NULL END), SUM(CASE WHEN DAYS_BETWEEN(TO_TIMESTAMP(JDT1.DueDate), CURRENT_TIMESTAMP) >= 120 THEN CASE WHEN JDT1.BalDueCred <> 0 THEN JDT1.BalDueCred * -1 ELSE TO_DECIMAL(JDT1.BalDueDeb, 22, 6) END ELSE NULL END)                                                                            	                                      	OLAP            	             	?          	?         	?           	?         	1,382      	0.39219214721137186  
        JOIN          	JOIN CONDITION: (INNER many-to-one) JDT1.ShortName = OCRD.CardCode                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        	                                      	OLAP            	             	?          	?         	?           	?         	3,453,618  	0.0016443543925119804
          COLUMN TABLE	[FACT]                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    	                                      	OLAP            	HXE          	REFACTOR   	JDT1      	COLUMN TABLE	3,453,618 	3,453,618  	?                    
          COLUMN TABLE	FILTER CONDITION: OCRD.CardType = 'c'                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                     	                                      	OLAP            	HXE          	REFACTOR   	OCRD      	COLUMN TABLE	1,382     	1,382      	?                    

*/