set schema refactor;
-- step 10 - change current_timestamp to current_date to avoid implicit type conversion

drop function balance_from_credits_debits;

create function balance_from_credits_debits 
            (IN CREDITS DECIMAL(19,6)
           , IN DEBITS DECIMAL(19,6))
        
        returns balance DECIMAL(19,6) 
as 
begin
    balance = case 
                when :CREDITS != 0.0 
                then TO_DECIMAL (:CREDITS * -1.0, 19, 6)
                else :DEBITS
              end;
end;

WITH _customer_debits_credits
("Customer Code", "Customer Name", "SYSCred", "SYSDeb", "BalDueCred", "BalDueDeb", "Due Days") AS 
    (SELECT 
          OCRD."CardCode" AS "Customer Code"
        , OCRD."CardName" AS "Customer Name"
        , JDT1."SYSCred"
        , JDT1."SYSDeb"
        , JDT1."BalDueCred"
        , JDT1."BalDueDeb"
        , DAYS_BETWEEN(JDT1."DueDate", current_date) AS "Due Days"
     FROM 
            JDT1 INNER JOIN  OCRD 
        ON  JDT1."ShortName" = OCRD."CardCode" 
        AND OCRD."CardType" = 'c' 
    )

SELECT 
      "Customer Code"
    , "Customer Name"
    , SUM( balance_from_credits_debits("SYSCred", "SYSDeb" )) AS "Balance Due"
    , SUM(CASE 
            WHEN ("Due Days" < 0)
            THEN balance_from_credits_debits("BalDueCred", "BalDueDeb")
          END) AS "Future Remit"
    , SUM(CASE 
            WHEN ("Due Days" BETWEEN 0 AND 30) 
            THEN balance_from_credits_debits("BalDueCred", "BalDueDeb")
          END) AS "0-30 days"
    , SUM(CASE 
            WHEN ("Due Days" BETWEEN 31 AND 60) 
            THEN balance_from_credits_debits("BalDueCred", "BalDueDeb")
          END) AS "31 to 60 days"
    , SUM(CASE 
            WHEN ("Due Days" BETWEEN 61 AND 90) 
            THEN balance_from_credits_debits("BalDueCred", "BalDueDeb")
          END) AS "61 to 90 days"
    , SUM(CASE 
            WHEN ("Due Days" BETWEEN 91 AND 120) 
            THEN balance_from_credits_debits("BalDueCred", "BalDueDeb")
          END) AS "91 to 120 days"
    , SUM(CASE 
            WHEN ("Due Days" > 121)
            THEN balance_from_credits_debits("BalDueCred", "BalDueDeb")
           END) AS "121+ days" 
FROM 
    _customer_debits_credits
GROUP BY 
      "Customer Code"
    , "Customer Name" 
HAVING 
    SUM( balance_from_credits_debits("SYSCred", "SYSDeb" ) )  != 0 
ORDER BY 
    "Customer Code";

/*
--> small data set

OPERATOR_NAME         	OPERATOR_DETAILS                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                 	OPERATOR_PROPERTIES                   	EXECUTION_ENGINE	TABLE_NAME	TABLE_TYPE  	TABLE_SIZE	OUTPUT_SIZE        	SUBTREE_COST          
COLUMN SEARCH         	_CUSTOMER_DEBITS_CREDITS.Customer Code, _CUSTOMER_DEBITS_CREDITS.Customer Name, SUM("REFACTOR"."BALANCE_FROM_CREDITS_DEBITS"(_CUSTOMER_DEBITS_CREDITS.SYSCred, _CUSTOMER_DEBITS_CREDITS.SYSDeb).BALANCE), SUM(CASE WHEN DAYS_BETWEEN(JDT1.DueDate, CURRENT_DATE) < 0 THEN "REFACTOR"."BALANCE_FROM_CREDITS_DEBITS"(_CUSTOMER_DEBITS_CREDITS.BalDueCred, _CUSTOMER_DEBITS_CREDITS.BalDueDeb).BALANCE ELSE 0.00 END), SUM(CASE WHEN DAYS_BETWEEN(JDT1.DueDate, CURRENT_DATE) >= 0 AND DAYS_BETWEEN(JDT1.DueDate, CURRENT_DATE) <= 30 THEN "REFACTOR"."BALANCE_FROM_CREDITS_DEBITS"(_CUSTOMER_DEBITS_CREDITS.BalDueCred, _CUSTOMER_DEBITS_CREDITS.BalDueDeb).BALANCE ELSE NULL END), SUM(CASE WHEN DAYS_BETWEEN(JDT1.DueDate, CURRENT_DATE) >= 31 AND DAYS_BETWEEN(JDT1.DueDate, CURRENT_DATE) <= 60 THEN "REFACTOR"."BALANCE_FROM_CREDITS_DEBITS"(_CUSTOMER_DEBITS_CREDITS.BalDueCred, _CUSTOMER_DEBITS_CREDITS.BalDueDeb).BALANCE ELSE NULL END), SUM(CASE WHEN DAYS_BETWEEN(JDT1.DueDate, CURRENT_DATE) >= 61 AND DAYS_BETWEEN(JDT1.DueDate, CURRENT_DATE) <= 90 THEN "REFACTOR"."BALANCE_FROM_CREDITS_DEBITS"(_CUSTOMER_DEBITS_CREDITS.BalDueCred, _CUSTOMER_DEBITS_CREDITS.BalDueDeb).BALANCE ELSE NULL END), SUM(CASE WHEN DAYS_BETWEEN(JDT1.DueDate, CURRENT_DATE) >= 91 AND DAYS_BETWEEN(JDT1.DueDate, CURRENT_DATE) <= 120 THEN "REFACTOR"."BALANCE_FROM_CREDITS_DEBITS"(_CUSTOMER_DEBITS_CREDITS.BalDueCred, _CUSTOMER_DEBITS_CREDITS.BalDueDeb).BALANCE ELSE NULL END), SUM(CASE WHEN DAYS_BETWEEN(JDT1.DueDate, CURRENT_DATE) > 121 THEN "REFACTOR"."BALANCE_FROM_CREDITS_DEBITS"(_CUSTOMER_DEBITS_CREDITS.BalDueCred, _CUSTOMER_DEBITS_CREDITS.BalDueDeb).BALANCE ELSE NULL END)                       	LATE MATERIALIZATION, ENUM_BY: CS_JOIN	OLAP            	?         	?           	?         	44                 	0.01320468453294249   
  ORDER BY            	_CUSTOMER_DEBITS_CREDITS.Customer Code ASC                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                       	                                      	OLAP            	?         	?           	?         	44                 	0.012866665443742492  
    HAVING            	SUM("REFACTOR"."BALANCE_FROM_CREDITS_DEBITS"(_CUSTOMER_DEBITS_CREDITS.SYSCred, _CUSTOMER_DEBITS_CREDITS.SYSDeb).BALANCE) != 0                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    	                                      	OLAP            	?         	?           	?         	44                 	0.012865218694363552  
      AGGREGATION     	GROUPING: _CUSTOMER_DEBITS_CREDITS.Customer Code, _CUSTOMER_DEBITS_CREDITS.Customer Name, AGGREGATION: SUM("REFACTOR"."BALANCE_FROM_CREDITS_DEBITS"(_CUSTOMER_DEBITS_CREDITS.SYSCred, _CUSTOMER_DEBITS_CREDITS.SYSDeb).BALANCE), SUM(CASE WHEN DAYS_BETWEEN(JDT1.DueDate, CURRENT_DATE) < 0 THEN "REFACTOR"."BALANCE_FROM_CREDITS_DEBITS"(_CUSTOMER_DEBITS_CREDITS.BalDueCred, _CUSTOMER_DEBITS_CREDITS.BalDueDeb).BALANCE ELSE 0.00 END), SUM(CASE WHEN DAYS_BETWEEN(JDT1.DueDate, CURRENT_DATE) >= 0 AND DAYS_BETWEEN(JDT1.DueDate, CURRENT_DATE) <= 30 THEN "REFACTOR"."BALANCE_FROM_CREDITS_DEBITS"(_CUSTOMER_DEBITS_CREDITS.BalDueCred, _CUSTOMER_DEBITS_CREDITS.BalDueDeb).BALANCE ELSE NULL END), SUM(CASE WHEN DAYS_BETWEEN(JDT1.DueDate, CURRENT_DATE) >= 31 AND DAYS_BETWEEN(JDT1.DueDate, CURRENT_DATE) <= 60 THEN "REFACTOR"."BALANCE_FROM_CREDITS_DEBITS"(_CUSTOMER_DEBITS_CREDITS.BalDueCred, _CUSTOMER_DEBITS_CREDITS.BalDueDeb).BALANCE ELSE NULL END), SUM(CASE WHEN DAYS_BETWEEN(JDT1.DueDate, CURRENT_DATE) >= 61 AND DAYS_BETWEEN(JDT1.DueDate, CURRENT_DATE) <= 90 THEN "REFACTOR"."BALANCE_FROM_CREDITS_DEBITS"(_CUSTOMER_DEBITS_CREDITS.BalDueCred, _CUSTOMER_DEBITS_CREDITS.BalDueDeb).BALANCE ELSE NULL END), SUM(CASE WHEN DAYS_BETWEEN(JDT1.DueDate, CURRENT_DATE) >= 91 AND DAYS_BETWEEN(JDT1.DueDate, CURRENT_DATE) <= 120 THEN "REFACTOR"."BALANCE_FROM_CREDITS_DEBITS"(_CUSTOMER_DEBITS_CREDITS.BalDueCred, _CUSTOMER_DEBITS_CREDITS.BalDueDeb).BALANCE ELSE NULL END), SUM(CASE WHEN DAYS_BETWEEN(JDT1.DueDate, CURRENT_DATE) > 121 THEN "REFACTOR"."BALANCE_FROM_CREDITS_DEBITS"(_CUSTOMER_DEBITS_CREDITS.BalDueCred, _CUSTOMER_DEBITS_CREDITS.BalDueDeb).BALANCE ELSE NULL END)	                                      	OLAP            	?         	?           	?         	45                 	0.012864707330727188  
        JOIN          	JOIN CONDITION: (INNER) JDT1.ShortName = OCRD.CardCode                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                           	                                      	OLAP            	?         	?           	?         	117,452.99999999999	0.00014780494248429349
          COLUMN TABLE	[FACT]                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                           	                                      	OLAP            	JDT1      	COLUMN TABLE	112,455   	112,455            	?                     
          COLUMN TABLE	FILTER CONDITION: OCRD.CardType = 'c'                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            	                                      	OLAP            	OCRD      	COLUMN TABLE	45        	45                 	?                     
*/

/*
--> large data set

OPERATOR_NAME         	OPERATOR_DETAILS                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          	OPERATOR_PROPERTIES                   	EXECUTION_ENGINE	DATABASE_NAME	SCHEMA_NAME	TABLE_NAME	TABLE_TYPE  	TABLE_SIZE	OUTPUT_SIZE	SUBTREE_COST         
COLUMN SEARCH         	_CUSTOMER_DEBITS_CREDITS.Customer Code, _CUSTOMER_DEBITS_CREDITS.Customer Name, SUM("REFACTOR"."BALANCE_FROM_CREDITS_DEBITS"(_CUSTOMER_DEBITS_CREDITS.SYSCred, _CUSTOMER_DEBITS_CREDITS.SYSDeb).BALANCE), SUM(CASE WHEN DAYS_BETWEEN(JDT1.DueDate, CURRENT_DATE) < 0 THEN "REFACTOR"."BALANCE_FROM_CREDITS_DEBITS"(_CUSTOMER_DEBITS_CREDITS.BalDueCred, _CUSTOMER_DEBITS_CREDITS.BalDueDeb).BALANCE ELSE 0.00 END), SUM(CASE WHEN DAYS_BETWEEN(JDT1.DueDate, CURRENT_DATE) >= 0 AND DAYS_BETWEEN(JDT1.DueDate, CURRENT_DATE) <= 30 THEN "REFACTOR"."BALANCE_FROM_CREDITS_DEBITS"(_CUSTOMER_DEBITS_CREDITS.BalDueCred, _CUSTOMER_DEBITS_CREDITS.BalDueDeb).BALANCE ELSE NULL END), SUM(CASE WHEN DAYS_BETWEEN(JDT1.DueDate, CURRENT_DATE) >= 31 AND DAYS_BETWEEN(JDT1.DueDate, CURRENT_DATE) <= 60 THEN "REFACTOR"."BALANCE_FROM_CREDITS_DEBITS"(_CUSTOMER_DEBITS_CREDITS.BalDueCred, _CUSTOMER_DEBITS_CREDITS.BalDueDeb).BALANCE ELSE NULL END), SUM(CASE WHEN DAYS_BETWEEN(JDT1.DueDate, CURRENT_DATE) >= 61 AND DAYS_BETWEEN(JDT1.DueDate, CURRENT_DATE) <= 90 THEN "REFACTOR"."BALANCE_FROM_CREDITS_DEBITS"(_CUSTOMER_DEBITS_CREDITS.BalDueCred, _CUSTOMER_DEBITS_CREDITS.BalDueDeb).BALANCE ELSE NULL END), SUM(CASE WHEN DAYS_BETWEEN(JDT1.DueDate, CURRENT_DATE) >= 91 AND DAYS_BETWEEN(JDT1.DueDate, CURRENT_DATE) <= 120 THEN "REFACTOR"."BALANCE_FROM_CREDITS_DEBITS"(_CUSTOMER_DEBITS_CREDITS.BalDueCred, _CUSTOMER_DEBITS_CREDITS.BalDueDeb).BALANCE ELSE NULL END), SUM(CASE WHEN DAYS_BETWEEN(JDT1.DueDate, CURRENT_DATE) > 121 THEN "REFACTOR"."BALANCE_FROM_CREDITS_DEBITS"(_CUSTOMER_DEBITS_CREDITS.BalDueCred, _CUSTOMER_DEBITS_CREDITS.BalDueDeb).BALANCE ELSE NULL END)	LATE MATERIALIZATION, ENUM_BY: CS_JOIN	OLAP            	HXE          	?          	?         	?           	?         	1,381      	0.3273790943751432   
  ORDER BY            	_CUSTOMER_DEBITS_CREDITS.Customer Code ASC                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                	                                      	OLAP            	             	?          	?         	?           	?         	1,381      	0.31707376796184317  
    HAVING            	SUM("REFACTOR"."BALANCE_FROM_CREDITS_DEBITS"(_CUSTOMER_DEBITS_CREDITS.SYSCred, _CUSTOMER_DEBITS_CREDITS.SYSDeb).BALANCE) != 0                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                             	                                      	OLAP            	             	?          	?         	?           	?         	1,381      	0.3169870051659172   
      AGGREGATION     	GROUPING: _CUSTOMER_DEBITS_CREDITS.Customer Code, AGGREGATION: SUM("REFACTOR"."BALANCE_FROM_CREDITS_DEBITS"(_CUSTOMER_DEBITS_CREDITS.SYSCred, _CUSTOMER_DEBITS_CREDITS.SYSDeb).BALANCE), SUM(CASE WHEN DAYS_BETWEEN(JDT1.DueDate, CURRENT_DATE) < 0 THEN "REFACTOR"."BALANCE_FROM_CREDITS_DEBITS"(_CUSTOMER_DEBITS_CREDITS.BalDueCred, _CUSTOMER_DEBITS_CREDITS.BalDueDeb).BALANCE ELSE 0.00 END), SUM(CASE WHEN DAYS_BETWEEN(JDT1.DueDate, CURRENT_DATE) >= 0 AND DAYS_BETWEEN(JDT1.DueDate, CURRENT_DATE) <= 30 THEN "REFACTOR"."BALANCE_FROM_CREDITS_DEBITS"(_CUSTOMER_DEBITS_CREDITS.BalDueCred, _CUSTOMER_DEBITS_CREDITS.BalDueDeb).BALANCE ELSE NULL END), SUM(CASE WHEN DAYS_BETWEEN(JDT1.DueDate, CURRENT_DATE) >= 31 AND DAYS_BETWEEN(JDT1.DueDate, CURRENT_DATE) <= 60 THEN "REFACTOR"."BALANCE_FROM_CREDITS_DEBITS"(_CUSTOMER_DEBITS_CREDITS.BalDueCred, _CUSTOMER_DEBITS_CREDITS.BalDueDeb).BALANCE ELSE NULL END), SUM(CASE WHEN DAYS_BETWEEN(JDT1.DueDate, CURRENT_DATE) >= 61 AND DAYS_BETWEEN(JDT1.DueDate, CURRENT_DATE) <= 90 THEN "REFACTOR"."BALANCE_FROM_CREDITS_DEBITS"(_CUSTOMER_DEBITS_CREDITS.BalDueCred, _CUSTOMER_DEBITS_CREDITS.BalDueDeb).BALANCE ELSE NULL END), SUM(CASE WHEN DAYS_BETWEEN(JDT1.DueDate, CURRENT_DATE) >= 91 AND DAYS_BETWEEN(JDT1.DueDate, CURRENT_DATE) <= 120 THEN "REFACTOR"."BALANCE_FROM_CREDITS_DEBITS"(_CUSTOMER_DEBITS_CREDITS.BalDueCred, _CUSTOMER_DEBITS_CREDITS.BalDueDeb).BALANCE ELSE NULL END), SUM(CASE WHEN DAYS_BETWEEN(JDT1.DueDate, CURRENT_DATE) > 121 THEN "REFACTOR"."BALANCE_FROM_CREDITS_DEBITS"(_CUSTOMER_DEBITS_CREDITS.BalDueCred, _CUSTOMER_DEBITS_CREDITS.BalDueDeb).BALANCE ELSE NULL END)                 	                                      	OLAP            	             	?          	?         	?           	?         	1,382      	0.3169713006204627   
        JOIN          	JOIN CONDITION: (INNER many-to-one) JDT1.ShortName = OCRD.CardCode                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        	                                      	OLAP            	             	?          	?         	?           	?         	3,453,618  	0.0016443543925119804
          COLUMN TABLE	[FACT]                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    	                                      	OLAP            	HXE          	REFACTOR   	JDT1      	COLUMN TABLE	3,453,618 	3,453,618  	?                    
          COLUMN TABLE	FILTER CONDITION: OCRD.CardType = 'c'                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                     	                                      	OLAP            	HXE          	REFACTOR   	OCRD      	COLUMN TABLE	1,382     	1,382      	?                    
*/